### ISSUE TITLE
Unable npm run app

### ISSUE THREAD

**Issue by EugeneGohh** [FrontendMasters/fullstack-graphql#32]
Hi guys, I have been stuck in this issue for quite a while now. I was following the course and after taking down the repo I got this after running `npm run app`:
![Untitled](https://user-images.githubusercontent.com/64187129/120356486-f7ebad00-c336-11eb-9277-cf11cdb2c583.png)

I have run `npm install` too.

**Comment by svikas641** [comment]
if you were able to fix the issue, you should post your answer too.

**Comment by svikas641** [comment]
If anyone else is facing this issue, try this approach it worked for me https://stackoverflow.com/questions/66459081/parcel-semver-bug
