### ISSUE TITLE
I get the error “deasync: command failed” when running “yarn install” on latest node v13.9.0

### ISSUE THREAD

**Issue by stormwatch** [FrontendMasters/fullstack-graphql#9]
Hi. I ~~am~~  was using latest node version 13.9.0
When I switched back to LTS (v12.16.1) `yarn install` finished without errors; so, feel free to close this if it is not a bug.

I think the relevant parts of the error output are:
```
error /usr/local/src/Frontend Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /usr/local/src/Frontend Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/deasync
```

and
```
make: Entering directory '/usr/local/src/Frontend Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
g++: error: Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/node-addon-api: No such file or directory
make: *** [deasync.target.mk:109: Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory '/usr/local/src/Frontend Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/deasync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eze/.config/nvm/13.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.17-200.fc31.x86_64
gyp ERR! command "/home/eze/.config/nvm/13.9.0/bin/node" "/home/eze/.config/nvm/13.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/src/Frontend Masters/courses/GraphQL/2019-11-25-server-graphql-nodejs/fullstack-graphql/node_modules/deasync
gyp ERR! node -v v13.9.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
Build failed
```
See [yarn-install.log](https://github.com/FrontendMasters/fullstack-graphql/files/4268565/yarn-install.log) for the full output of running `yarn install`.

**Comment by WonderfulOlanrewaju** [comment]
There is a new release of Node version 14.2.0 you can download it at https://nodejs.org/en/ it solves the issue

**Comment by nikhilbhati** [comment]
I have also tired with latest version but no luck still getting the same error .

**Comment by WonderfulOlanrewaju** [comment]
The latest node is now 14.3.0 I am not sure if that release doesn't have same issue as versions that bring out this issue in first place. However, version 12.17.0 and version 14.2.0 should bypass this error try use either of those two versions.

**Comment by MujunZ** [comment]
I got this issue as well and `12.17.0` worked for me. Thanks!

**Comment by eriestrisnadi** [comment]
Just try to remove `yarn.lock` and reinstall again using `yarn install`.

**Comment by doantruongminh** [comment]
I have also tired with latest version but no luck still getting the same error .

**Comment by stormwatch** [comment]
>  When I switched back to LTS (v12.16.1) yarn install finished without errors; so, feel free to close this if it is not a bug.

As I said in my first message, the code works with the node 12.16.1 and even with other versions. Therefore, I close this issue since it was never intended for the code to be compatible with every node runtime update.

**Comment by myst729** [comment]
I encountered this issue and I guess the reason is because I use Mac M1. The downloaded bins are for intel CPU Macs.

**Comment by Kasopej** [comment]
Thanks guys! This thread helped me find a quick answer to my package installation issue! :+1:

**Comment by myst729** [comment]
My fix is to install node-gyp globally with yarn. Yarn doesn't care if you did `npm i -g node-gyp`.

**Comment by scolestock** [comment]
Had same issue, and `pnpm add node-gyp --global` worked here as well.

**Comment by kolesrdjanov** [comment]
> My fix is `yarn global add node-gyp`. Yarn doesn't care if you did `npm i -g node-gyp`.

This worked for me, thanks a bunch!

**Comment by aziesemer** [comment]
The only thing that worked for me was downgrading node:
```
$ brew uninstall node@22
$ brew install node@20 
```
